version: "3.3"

services:
  api:
    build:
      context: ./api
    container_name: api
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api/api/healthcheck" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
      HIDE_PRISMA_LOGS: ${HIDE_PRISMA_LOGS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASS: ${REDIS_PASS}
      REDIS_PORT: ${REDIS_PORT}
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - ${API_PORT}:3000
      - ${PRISMA_STUDIO_PORT}:5555
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      api-network:
        ipv4_address: "10.5.0.8"
    command: npm run watch

  db:
    image: postgres
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "devuser" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POGRES_PORT}:5432
    networks:
      api-network:
        ipv4_address: "10.5.0.6"
    volumes: 
      - ./.volumes/dabatase/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASS}
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    ports:
     - ${REDIS_PORT}:6379
    environment:
     - REDIS_REPLICATION_MODE=${REDIS_REPLICATION_MODE}
     - REDIS_PASS=${REDIS_PASS}
    networks:
      api-network:
        ipv4_address: "10.5.0.10"
    volumes:
      - ./.volumes/database/redis:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  db:
    driver: local

# Workaround for prisma and Apple Silicon issue
networks:
  api-network:
    driver: bridge
    ipam:
     config:
       - subnet: "10.5.0.0/16"
         gateway: "10.5.0.1"
